eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.1.14.46:8761/eureka/
  instance:
    hostname: 10.1.14.46
    

microservice:
  PAYMENT-SERVICE:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment

  ORDER-SERVICE:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/payment/doPayment    
    
